export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const REMOVE_USERS_START = 'REMOVE_USERS_START';
export const REMOVE_USERS_SUCCESS = 'REMOVE_USERS_SUCCESS';
export const REMOVE_USERS_ERROR = 'REMOVE_USERS_ERROR';
