export const GET_PROGRAMS_SUCCESS = 'GET_PROGRAMS_SUCCESS';
export const GET_PROGRAMS_START = 'GET_PROGRAMS_START';
export const GET_PROGRAMS_ERROR = 'GET_PROGRAMS_ERROR';
export const REMOVE_PROGRAM_SUCCESS = 'REMOVE_PROGRAM_SUCCESS';
export const REMOVE_PROGRAM_ERROR = 'REMOVE_PROGRAM_ERROR';
export const ADD_PROGRAM = 'ADD_PROGRAM';
